# Generated by Django 3.2.5 on 2021-11-08 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0002_alter_students_phonenumber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
