# Generated by Django 3.2.5 on 2021-11-08 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0003_rename_students_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='city',
            new_name='grades',
        ),
    ]
